Repository RebeccaJasper/Lab-Project-19G06, pull requests merged in 2019-08, with the labels that each got.

#52 Added instructions page for data collection process
  mobile_application/static/CSS/instructions.css
  mobile_application/static/js/consent.js
  mobile_application/static/js/instructions.js
  mobile_application/templates/instructions.html
  mobile_application/views.py
Labels: User Story

#50 Display random faces for data collection
  mobile_application/db.py
  mobile_application/facial_images/1-remove-bg.png
  mobile_application/facial_images/1.jpg
  mobile_application/models.py
  mobile_application/static/CSS/base-layout.css
  mobile_application/static/CSS/photo.css
  mobile_application/static/js/photo.js
  mobile_application/templates/photo.html
  mobile_application/views.py
  tests/test_sample.py
Labels: User Story

#65 Identi-Kreate submit button added
  mobile_application/static/CSS/identikreate.css
  mobile_application/static/js/GUI.js
  mobile_application/static/js/explanation.js
  mobile_application/templates/index.html
Labels: Technical Task, User Story

#68 Server deployment and Database Configuration
  mobile_application/db.py
  mobile_application/facial_images/2.jpg
  mobile_application/facial_images/3.jpg
  mobile_application/models.py
  mobile_application/views.py
  requirements.txt
Labels: Technical Task

#67 Encoding of statement features
  mobile_application/static/js/statement.js
  mobile_application/templates/statement.html
Labels: Technical Task

#76 Identikit Submission
  .vscode/settings.json
  mobile_application/controller.py
  mobile_application/face_encoding/normalization.py
  mobile_application/models.py
  mobile_application/static/js/GUI.js
  mobile_application/static/js/gameLogic.js
  mobile_application/static/js/statement.js
  mobile_application/static/js/submit.js
  mobile_application/templates/finish.html
  mobile_application/templates/identi-kreate.html
  mobile_application/templates/statement.html
  mobile_application/views.py
Labels: Technical Task

#83 Identikit Refinement
  docs/Submitted facial markers.jpg
  mobile_application/static/js/GUI.js
  mobile_application/static/js/brows.js
  mobile_application/static/js/eyes.js
  mobile_application/static/js/face.js
  mobile_application/static/js/gameLogic.js
  mobile_application/static/js/mouth.js
  mobile_application/static/js/nose.js
  mobile_application/static/js/shadows.js
  mobile_application/templates/identi-kreate.html
Labels: Technical Task, User Story

#84 Calculating distance matrix
  mobile_application/clustering/dissimilarity.py
  mobile_application/clustering/feature_encoding.py
  mobile_application/clustering/feature_weighting.py
  mobile_application/clustering/hierarchical_clusterring.py
  mobile_application/controller.py
  mobile_application/models.py
  mobile_application/static/js/statement.js
  tests/__init__.py
  tests/test_dissimilarity.py
Labels: Technical Task

#86 Mobile reactivity for Identi.Fi webapp
  mobile_application/static/CSS/consent.css
  mobile_application/static/CSS/explanation.css
  mobile_application/static/CSS/home.css
  mobile_application/static/CSS/identikreate.css
  mobile_application/static/CSS/instructions.css
  mobile_application/static/CSS/photo.css
  mobile_application/static/CSS/statement.css
  mobile_application/static/js/home.js
  mobile_application/templates/consent.html
  mobile_application/templates/explanation.html
  mobile_application/templates/finish.html
  mobile_application/templates/home.html
  mobile_application/templates/identi-kreate.html
  mobile_application/templates/instructions.html
  mobile_application/templates/photo.html
  mobile_application/templates/statement.html
Labels: Technical Task

#85 One-way routing
  mobile_application/static/js/consent.js
  mobile_application/static/js/explanation.js
  mobile_application/static/js/home.js
  mobile_application/static/js/instructions.js
  mobile_application/static/js/photo.js
  mobile_application/static/js/statement.js
  mobile_application/static/js/submit.js
Labels: Technical Task

#87 Minor changes in preparation for data collection
  mobile_application/static/CSS/consent.css
  mobile_application/static/CSS/explanation.css
  mobile_application/static/CSS/home.css
  mobile_application/static/CSS/identikreate.css
  mobile_application/static/CSS/instructions.css
  mobile_application/static/CSS/photo.css
  mobile_application/static/CSS/statement.css
  mobile_application/static/favicon.ico
  mobile_application/static/favicon1.ico
  mobile_application/static/img/home-page.jpg
  mobile_application/static/img/home-page2.jpg
  mobile_application/static/js/brows.js
  mobile_application/static/js/consent.js
  mobile_application/static/js/explanation.js
  mobile_application/static/js/gameLogic.js
  mobile_application/static/js/home.js
  mobile_application/static/js/instructions.js
  mobile_application/static/js/nose.js
  mobile_application/static/js/photo.js
  mobile_application/static/js/shadows.js
  mobile_application/static/js/statement.js
  mobile_application/static/js/submit.js
  mobile_application/templates/consent.html
  mobile_application/templates/explanation.html
  mobile_application/templates/finish.html
  mobile_application/templates/home.html
  mobile_application/templates/identi-kreate.html
  mobile_application/templates/instructions.html
  mobile_application/templates/photo.html
  mobile_application/templates/statement.html
Labels: Technical Task

#88 Connection Pooling
  mobile_application/db.py
Labels: Technical Task

#89 Limited number of database respondents
  mobile_application/models.py
Labels: Technical Task

#90 Bug of Identi-Kreate window crashing fixed
  mobile_application/static/CSS/instructions.css
  mobile_application/static/js/GUI.js
  mobile_application/static/js/gameLogic.js
  mobile_application/templates/instructions2.html
Labels: Bug, Technical Task

#92 Fix for screen resolution issues
  mobile_application/static/CSS/home.css
  mobile_application/static/CSS/instructions.css
  mobile_application/templates/instructions2.html
Labels: Bug, Technical Task

#93 Identi-Match Front-End
  mobile_application/static/CSS/submission-info.css
  mobile_application/static/CSS/submissions.css
  mobile_application/static/img/identikit.jpg
  mobile_application/static/js/submission-info.js
  mobile_application/static/js/submissions.js
  mobile_application/templates/submission-info.html
  mobile_application/templates/submissions.html
  mobile_application/views.py
Labels: Technical Task, User Story

#100 Identi-Match V.1
  application.py
  mobile_application/clustering/README.md
  mobile_application/clustering/dissimilarity.py
  mobile_application/clustering/face_clustering.py
  mobile_application/clustering/feature_encoding.py
  mobile_application/clustering/feature_weighting.py
  mobile_application/clustering/hierarchical_clusterring.py
  mobile_application/controller.py
  mobile_application/db.py
  mobile_application/face_encoding/README.md
  mobile_application/face_encoding/coordinates.py
  mobile_application/face_encoding/normalization.py
  mobile_application/models.py
  mobile_application/static/js/submission-info.js
  mobile_application/static/js/submissions.js
  mobile_application/views.py
Labels: Technical Task, User Story

#102 Front End for Repeat Offender Display
  mobile_application/controller.py
  mobile_application/static/CSS/explanation.css
  mobile_application/static/CSS/submission-info.css
  mobile_application/static/CSS/submissions.css
  mobile_application/static/js/submission-info.js
  mobile_application/static/js/submissions.js
  mobile_application/templates/submission-info.html
  mobile_application/templates/submissions.html
  mobile_application/views.py
Labels: Technical Task

#103 Repeat offenders can be identified
  mobile_application/clustering/dissimilarity.py
  mobile_application/controller.py
  mobile_application/db.py
  mobile_application/models.py
  mobile_application/static/CSS/submission-info.css
  mobile_application/static/js/submission-info.js
  mobile_application/templates/submission-info.html
  mobile_application/views.py
Labels: Technical Task
